apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: cscp-any-allow-cscp-shared-ns-g-np
  labels:
    {{- include "dc15-nonprd-c1.labels" . | nindent 4}}
  {{- with .Values.cscp.labels}}
  {{- toYaml . | nindent 4}}
  {{- end}}
  {{- with .Values.cscp.labels}}
  {{- toYaml . | nindent 4}}
  {{- end}}
spec:
  namespaceSelector: has(field.cattle.io/projectId) && field.cattle.io/projectId in { "{{.Values.cscp.shared.rancherProjectID}}" }
  types:
    - Ingress
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        namespaceSelector: has(field.cattle.io/projectId) && field.cattle.io/projectId in {"p-2tzxr" , "p-xgq74" , "p-926wp"}
