apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: cscp-shared-allow-cscp-any-ns-g-np
  labels:
    {{- include "dc15-nonprd-c1.labels.labels" . | nindent 4}}
  {{- with .Values.cscp.labels}}
  {{- toYaml . | nindent 4}}
  {{- end}}
  {{- with .Values.cscp.labels}}
  {{- toYaml . | nindent 4}}
  {{- end}}
spec:
  namespaceSelector: has(field.cattle.io/projectId) && field.cattle.io/projectId in {"p-x264d" , "p-6dcg" , "p-rjhmm"}
  types:
    - Ingress
  ingress:
    - action: Allow
      # protocol: TCP
      source:
        namespaceSelector: has(field.cattle.io/projectId) && field.cattle.io/projectId in { "{{.Values.cscp.shared.rancherProjectID}}" } 